config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, param: :slug, except: :destroy do
    member do
      post 'vote'
    end

    resources :comments, only: :create do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

  sluggable_column :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true 
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true
  validates :url, uniqueness: true

  sluggable_column :title
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable

  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: { minimum: 5 }

  sluggable_column :username

  def admin?
    self.role == 'admin'
  end

  def moderator?
    self.role == 'moderator'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    access_denied unless logged_in?
  end

  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end

  def display_flash_for_vote(vote)
    if vote.valid?
      flash.now[:notice] = "Your vote was counted"
    else
      flash.now[:error] = "You can't vote on that more than once"
    end
  end

  def access_denied
    flash[:error] = "You can't do that"
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]

  def show
    @category = Category.find_by slug: params[:id]
  end  

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category has been created"
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by slug: params[:post_slug]
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user
    
    if @comment.save
      flash[:notice] = 'Your comment was added'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if vote.valid?
          flash[:notice] = "Your vote was counted"
        else
          flash[:error] = "You can only vote on a comment once"
        end
    
        redirect_back(fallback_location: root_path)
      end

      format.js do
        display_flash_for_vote(vote)
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by { |x| x.total_votes }.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(strong_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(strong_params)
      flash[:notice] = "The post has been updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @post)

    respond_to do |format|
      format.html do 
        if vote.valid?
          flash[:notice] = "Your vote was counted"
        else
          flash[:error] = "You can only vote on a post once"
        end
        redirect_back(fallback_location: root_path)
      end

      format.js do
        display_flash_for_vote(vote)
      end
    end
  end

  private

  def strong_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:slug]
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome! You're logged in"
      redirect_to root_path
    else
      flash.now[:error] = "There is something wrong with your username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've successfully logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You are registered"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :time_zone)
  end

  def set_user
    @user = User.find_by slug: params[:id]
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "You're not allowed to do that"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.start_with?(/https?:\/\//) ? str : "http://#{str}"
  end

  def display_datetime(dt)
    if logged_in? && !current_user.time_zone.blank?
      dt = dt.in_time_zone(current_user.time_zone)
    end

    dt.strftime("%d/%m/%Y %R %Z")
  end

  def ajax_flash(div_id)
    response = ''
    flash_div = ''

    flash.each do |name, msg|
      if msg.is_a?(String)
        flash_div = "<div class=\"alert alert-#{name == 'notice' ? 'success' : 'danger'} ajax_flash\"> <a class=\"close\" data-dismiss=\"alert\">&#215;</a> <div id=\"flash_#{name == 'notice' ? 'notice' : 'error'}\">#{h(msg)}</div> </div>" 
      end
    end

    response = "$('.alert').remove();$('#{div_id}').prepend('#{flash_div}');"
    response.html_safe
  end
end

app/views/categories/_category.html.erb
<span class="badge badge-primary">
  <%= link_to category.name, category_path(category) %>
</span>&nbsp;

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'New Category' %>
<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " » " + @category.name %>
<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class="row">
  <% if logged_in? %>
    <div class="col-2">
      <div class="card text-center bg-light">
        <div class="card-body">
          <%= render 'comments/up_arrow', comment: comment %>
          <br/>
          <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
          <br/>    
          <%= render 'comments/down_arrow', comment: comment %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-10">
    <div class="card">
      <div class="card-body">
        <p>
          <em>"<%= comment.body %>"</em>
          <% if show_post %>
            on <%= link_to comment.post.title, post_path(comment.post) %>
          <% end %>
        </p>
        <p>
          <span class="text-muted">by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
          <span class="text-muted">at <%= display_datetime(comment.created_at) %></span>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/comments/_down_arrow.html.erb
<%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: :post, remote: true do %>
  <svg class="bi bi-arrow-down text-dark" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M4.646 9.646a.5.5 0 01.708 0L8 12.293l2.646-2.647a.5.5 0 01.708.708l-3 3a.5.5 0 01-.708 0l-3-3a.5.5 0 010-.708z" clip-rule="evenodd"/>
    <path fill-rule="evenodd" d="M8 2.5a.5.5 0 01.5.5v9a.5.5 0 01-1 0V3a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
  </svg>
<% end %>

app/views/comments/_form.html.erb
<%= render 'shared/errors', obj: @comment %>

<%= form_for [@post, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :body, 'Enter a comment:' %>
    <%= f.text_area :body, class: 'form-control', rows: 5 %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/comments/_post_comments.html.erb
<h6>Comments</h6>

<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/comments/_up_arrow.html.erb
<%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: :post, remote: true do %>
  <svg class="bi bi-arrow-up text-dark" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v9a.5.5 0 01-1 0V4a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
    <path fill-rule="evenodd" d="M7.646 2.646a.5.5 0 01.708 0l3 3a.5.5 0 01-.708.708L8 3.707 5.354 6.354a.5.5 0 11-.708-.708l3-3z" clip-rule="evenodd"/>
  </svg>
<% end %>

app/views/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes");
<%= ajax_flash('#top-div') %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>">
      <a class='close' data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}"%>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <%= link_to "Postit!", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category), class: 'dropdown-item' %>
          <% end %>
          <% if logged_in? and current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to '+ New Category', new_category_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'New Post', new_post_path, class: 'nav-link btn btn-primary', style: "color: white" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit profile', edit_user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'View profile', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'Log out', logout_path, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Register', register_path, class: 'nav-link btn btn-primary', style: 'color: white' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
<nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Juliette's Post-It App</title>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main>
      <div class="container">
         <div class="row-fluid">
          <div class="span12" id ="top-div">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </main> <!--! end of #main -->
  </body>
</html>

app/views/posts/_down_arrow.html.erb
<%= link_to vote_post_path(post, vote: false), method: :post, remote: true do %>
  <svg class="bi bi-arrow-down text-dark" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M4.646 9.646a.5.5 0 01.708 0L8 12.293l2.646-2.647a.5.5 0 01.708.708l-3 3a.5.5 0 01-.708 0l-3-3a.5.5 0 010-.708z" clip-rule="evenodd"/>
    <path fill-rule="evenodd" d="M8 2.5a.5.5 0 01.5.5v9a.5.5 0 01-1 0V3a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
  </svg>
<% end %>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', rows: 5 %>
  </div>
  <div class='form-group'>
    <%= f.label 'Categories' %>
    <br/>
    <div class='form-check form-check-inline'>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: 'form-check-label') { cb.check_box(class: 'form-check-input') + cb.text } %>
      <% end %>
    </div>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
  <% if logged_in? %>
    <div class="col-sm-2">
      <div class="card text-center bg-light">
        <div class="card-body">
          <%= render 'posts/up_arrow', post: post %>
          <br/>
          <span id="post_<%= post.slug %>_votes" %><%= post.total_votes  %> votes</span>
          <br/>
          <%= render 'posts/down_arrow', post: post %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-sm-10">
    <div class="card">
      <div class="card-header">
        <%= render post.categories %>
        <h5><%= link_to post.title, fix_url(post.url) %></h5>
      </div>
      <div class="card-body">
        <p class="card-text"><%= post.description %></p>
        <p>
          <span class="text-muted">posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
          <span class="text-muted">at <%= display_datetime(post.created_at) %></span>
        </p>
        <small>
          <span>
            <%= link_to("#{post.comments.size} comments", post_path(post)) %>
          </span>
        </small>
      </div>
    </div>
  </div>
</div>

app/views/posts/_up_arrow.html.erb
<%= link_to vote_post_path(post, vote: true), method: :post, remote: true do %>
  <svg class="bi bi-arrow-up text-dark" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v9a.5.5 0 01-1 0V4a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
    <path fill-rule="evenodd" d="M7.646 2.646a.5.5 0 01.708 0l3 3a.5.5 0 01-.708.708L8 3.707 5.354 6.354a.5.5 0 11-.708-.708l3-3z" clip-rule="evenodd"/>
  </svg>
<% end %>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'New Post' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<p class="float-right">
  <%= link_to 'Edit Post', edit_post_path(@post) if logged_in? %>
</p>

<%= render @post.categories %>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>

<hr/>

<% if logged_in? %>
  <%= render 'comments/form' %>
<% end %>

<br/>

<%= render 'comments/post_comments' %>

app/views/posts/vote.js.erb
$("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> votes");
<%= ajax_flash('#top-div') %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  </hr>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger"> 
    <p>Please fix the following errors:</p>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :time_zone %>
    <%= f.time_zone_select :time_zone, nil, { default: Time.zone.name }, { class: 'form-control' } %>
  </div>
  <%= f.submit (@user.new_record? ? 'Register' : 'Update profile'), class: 'btn btn-primary' %>
<% end %>

app/views/users/_user.html.erb
<div class="card bg-light">
  <div class="card-body">
    <dl class="row">
      <dt class="col-4 text-right">Username:</dt>
      <dd class="col-8"><%= user.username %></dd>
      <dt class="col-4 text-right">Time zone:</dt>
      <dd class="col-8"><%= user.time_zone %></dd>
    </dl>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit profile' %>

<%= render 'shared/errors', obj: @user %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'shared/errors', obj: @user %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<%= render 'user', user: @user %>

<hr/>

<h6><%= @user.username %>'s Activity</h6>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user), class: "nav-link #{'active' if params[:tab].nil? }" %>
  </li>
  <li class="nav-item">
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments'), class: "nav-link #{'active' if params[:tab] == 'comments' }" %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <% @user.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
<% elsif params[:tab] == 'comments' %>
  <% @user.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment, show_post: true %>
  <% end %>
<% end %>